//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShubhKarya2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReg
    {
        public int Id { get; set; }
        public string SrNo { get; set; }
        public string OnBehalf { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Height { get; set; }
        public string Religion { get; set; }
        public string Caste { get; set; }
        public string MotherTongue { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Landmark { get; set; }
        public string PinCode { get; set; }
        public string Education { get; set; }
        public string Profession { get; set; }
        public string Income { get; set; }
        public string Img { get; set; }
        public string MaritalStatus { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string BloodGroup { get; set; }
        public string SkinComp { get; set; }
        public string TOB { get; set; }
        public string POB { get; set; }
        public string Rashi { get; set; }
        public string Nakshatra { get; set; }
        public string SubCaste { get; set; }
        public string Gotra { get; set; }
        public string Manglik { get; set; }
        public string College { get; set; }
        public string Organization { get; set; }
        public string FatherName { get; set; }
        public string FatherOccupation { get; set; }
        public string MotherName { get; set; }
        public string MotherOccupation { get; set; }
        public string TotalFamilyMember { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    }
}
