//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerAccount
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> MasterId { get; set; }
        public Nullable<decimal> PreveusBalance { get; set; }
        public Nullable<decimal> PaidBalance { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public string PaymentMode { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<System.DateTime> CrateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<decimal> NewInvoiceAmount { get; set; }
    }
}
