//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string OwnerName { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string Logo { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string GSTNo { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Password { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    }
}
