//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int Id { get; set; }
        public Nullable<int> MasterId { get; set; }
        public string Particular { get; set; }
        public string HSN { get; set; }
        public string UOM { get; set; }
        public string GST { get; set; }
        public decimal MRP { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<System.DateTime> CrateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
